update

diff --git a/packages/samplebootapp/packaging b/packages/samplebootapp/packaging
--- a/packages/samplebootapp/packaging
+++ b/packages/samplebootapp/packaging
@@ -1,1 +1,14 @@
-set -e
+#!/bin/bash
+# abort script on any command that exit with a non zero value
+set -e -x
+
+archive=`echo fe-time-tracking-*jar`
+
+if [[ -f $archive ]] ; then
+  echo "Archive found"
+else
+  echo "Archive not found"
+  exit 1
+fi
+
+cp -r $archive ${BOSH_INSTALL_TARGET}
